name: Java SDK

on:
  push:
    branches:
      - "*"
    paths:
      - "java-sdk/**"
  pull_request:
    paths:
      - "java-sdk/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build custom Docker image
        run: docker build -t hardhat-testnet deploy/hardhat-testnet/.

      - name: Build with Maven
        working-directory: java-sdk
        run: mvn clean install
